force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/TotalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalCost__c</fullName>
    <label>Total Cost</label>
    <summarizedField>Transaction_Item__c.ItemCost__c</summarizedField>
    <summaryForeignKey>Transaction_Item__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TotalDiscount__c.field-meta.xml
<CustomField>
    <fullName>TotalDiscount__c</fullName>
    <label>Total Discount</label>
    <summarizedField>Transaction_Item__c.Discount__c</summarizedField>
    <summaryForeignKey>Transaction_Item__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionCount__c.field-meta.xml
<CustomField>
    <fullName>TransactionCount__c</fullName>
    <label>Transaction Count</label>
    <summaryForeignKey>Transaction_Item__c.Transaction__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TI-{00}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Item__c/fields/ItemCost__c.field-meta.xml
<CustomField>
    <fullName>ItemCost__c</fullName>
    <label>Item Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TransactionCalloutServiceTest.cls
/**
 * Created by Benjamin Lin on 26/6/22.
 */

@IsTest
private class TransactionCalloutServiceTest {
    @TestSetup
    static void setupTestData(){

        Transaction__c trans = new Transaction__c(TransactionDate__c = Date.today());
        insert trans;

        Transaction_Item__c transactionItem = new Transaction_Item__c();
        transactionItem.Transaction__c = trans.Id;
        transactionItem.ItemCost__c = 1000;
        transactionItem.Discount__c = 10;
        insert transactionItem;
    }

    // Test successful post
    @IsTest
    static void testSuccess(){
        List<Transaction_Item__c> transactionItems = new List<Transaction_Item__c>([SELECT Id, ItemCost__c, Name
        FROM Transaction_Item__c]);

        List<Transaction__c> transactions = [SELECT Id, TransactionCount__c, TotalDiscount__c,
                TotalCost__c, TransactionDate__c FROM Transaction__c ];
        //Transaction__c trans = transactions[0];
        //String jsonTransactionItems = TransactionCalloutService.serializeTransactionItems(transactionItems);
        //String jsonTransactionHeader = TransactionCalloutService.serializeTransaction(trans);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new TransactionCalloutServiceMock());
        TransactionCalloutService.callTransactionService(transactionItems);
        //HttpResponse response = TransactionCalloutService.callOut(jsonTransactionItems);
        //TransactionCalloutService.callOutTrans(jsonTransactionHeader);
        Id jobID = System.enqueueJob(new TransactionCalloutService.QueueableCallout(transactions));
        Test.stopTest();

        System.assertEquals(1, transactionItems.size());
        System.assertNotEquals(null, jobID);
        //System.assertEquals(200, response.getStatusCode());
    }

    // Test failure post
    @IsTest
    static void testFailure(){
        List<Transaction_Item__c> transactionItems = new List<Transaction_Item__c>([SELECT Id, ItemCost__c, Name
        FROM Transaction_Item__c]);
        List<Transaction__c> transactions = [SELECT Id, TransactionCount__c, TotalDiscount__c,
                TotalCost__c, TransactionDate__c FROM Transaction__c ];

        Test.startTest();

        Test.setMock(HttpCalloutMock.class,new TransactionCalloutServiceMockFailure());
        TransactionCalloutService.callTransactionService(transactionItems);
        Id jobID = System.enqueueJob(new TransactionCalloutService.QueueableCallout(transactions));

        Test.stopTest();

        System.assertEquals(1, transactionItems.size());
        System.assertNotEquals(null, jobID);
    }

}